import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from "./lib/SessionProvider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div className={inter.className}>{children}</div>
        </SessionProvider>
      </body>
    </html>
  );
}
